-- DG OS Social Command Center schema.
-- Applied to Supabase project jzvnmhfhyvmmbontsoej.
-- Browser clients do not access these tables directly; the social Edge Function
-- uses the service role after validating a DG OS device session.

create table if not exists public.dgos_social_accounts (
  account_key text primary key check (account_key in ('business','private')),
  platform text not null default 'instagram' check (platform = 'instagram'),
  handle text,
  account_type text not null default 'unknown' check (account_type in ('business','creator','private','unknown')),
  source_mode text not null default 'export' check (source_mode in ('export','meta')),
  meta_user_id text,
  connected_at timestamptz,
  last_import_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.dgos_social_snapshots (
  id bigint generated by default as identity primary key,
  account_key text not null references public.dgos_social_accounts(account_key) on delete cascade,
  captured_at timestamptz not null default now(),
  followers_count integer not null check (followers_count >= 0),
  following_count integer not null check (following_count >= 0),
  source text not null default 'export' check (source in ('export','meta')),
  source_ref text
);

create index if not exists dgos_social_snapshots_account_time_idx
  on public.dgos_social_snapshots (account_key, captured_at desc);

create table if not exists public.dgos_social_relationships (
  account_key text not null references public.dgos_social_accounts(account_key) on delete cascade,
  username text not null,
  is_follower boolean not null default false,
  is_following boolean not null default false,
  whitelisted boolean not null default false,
  decision text check (decision is null or decision in ('keep','removed','later')),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  state_changed_at timestamptz not null default now(),
  primary key (account_key, username),
  check (username ~ '^[a-z0-9._]{1,30}$')
);

create index if not exists dgos_social_relationships_cleanup_idx
  on public.dgos_social_relationships (account_key, is_following, is_follower, whitelisted);

create table if not exists public.dgos_social_events (
  id bigint generated by default as identity primary key,
  account_key text not null references public.dgos_social_accounts(account_key) on delete cascade,
  event_type text not null check (event_type in ('new_follower','lost_follower','started_following','stopped_following')),
  username text not null,
  occurred_at timestamptz not null default now(),
  snapshot_id bigint references public.dgos_social_snapshots(id) on delete set null
);

create index if not exists dgos_social_events_account_time_idx
  on public.dgos_social_events (account_key, occurred_at desc);

alter table public.dgos_social_accounts enable row level security;
alter table public.dgos_social_snapshots enable row level security;
alter table public.dgos_social_relationships enable row level security;
alter table public.dgos_social_events enable row level security;

revoke all on public.dgos_social_accounts from anon, authenticated;
revoke all on public.dgos_social_snapshots from anon, authenticated;
revoke all on public.dgos_social_relationships from anon, authenticated;
revoke all on public.dgos_social_events from anon, authenticated;

grant select, insert, update, delete on public.dgos_social_accounts to service_role;
grant select, insert, update, delete on public.dgos_social_snapshots to service_role;
grant select, insert, update, delete on public.dgos_social_relationships to service_role;
grant select, insert, update, delete on public.dgos_social_events to service_role;
grant usage, select on all sequences in schema public to service_role;
