'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {allowedRelativePath}=require('./staticApp.js');
const root=require('node:path').join(__dirname,'../..');
const src=fs.readFileSync(root+'/cartesia-connect.js','utf8');
const html=fs.readFileSync(root+'/voice-studio.html','utf8');
assert.ok(html.includes('src="./cartesia-connect.js"'));
assert.equal(allowedRelativePath('/cartesia-connect.js'),'cartesia-connect.js');
assert.ok(src.includes('/functions/v1/jarvis-cartesia'));
assert.ok(src.includes('Authorization:'));
assert.ok(src.includes('email_confirmed_at'));
assert.ok(!src.includes('CARTESIA_API_KEY'));
assert.ok(!src.includes('X-API-Key'));
assert.ok(src.includes('length>300'));
console.log('Cartesia Studio wiring checks passed');
