'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {allowedRelativePath}=require('./staticApp.js');
const root=require('node:path').join(__dirname,'../..');
const client=fs.readFileSync(root+'/cartesia-favorites.js','utf8');
const html=fs.readFileSync(root+'/voice-studio.html','utf8');
assert.ok(html.includes('src="./cartesia-favorites.js'));
assert.equal(allowedRelativePath('/cartesia-favorites.js'),'cartesia-favorites.js');
assert.ok(client.includes('/functions/v1/jarvis-cartesia'));
assert.ok(client.includes("request('GET')"));
assert.ok(client.includes("request('POST'"));
assert.ok(client.includes('email_confirmed_at'));
assert.ok(!client.includes('CARTESIA_API_KEY'));
assert.ok(!client.includes('X-API-Key'));
assert.ok(client.includes('Clive')&&client.includes('Archie')&&client.includes('Skylar')&&client.includes('Lindiwe'));
console.log('Cartesia favourites wiring checks passed');
