'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'../..');
const html=fs.readFileSync(path.join(root,'voice-studio.html'),'utf8');
const js=fs.readFileSync(path.join(root,'voice-studio.js'),'utf8');
const main=fs.readFileSync(path.join(root,'index.html'),'utf8');
const routing=require('../lib/staticApp.js');
for(const provider of ['cartesia','elevenlabs','openai','browser'])assert.ok(html.includes('data-provider="'+provider+'"'));
assert.ok(html.includes('id="voiceSelect"'));
assert.ok(html.includes('id="preview"'));
assert.ok(main.includes('href="./voice-studio.html"'));
assert.equal(routing.allowedRelativePath('/voice-studio.html'),'voice-studio.html');
assert.equal(routing.allowedRelativePath('/voice-studio.js'),'voice-studio.js');
assert.ok(!/api[_-]?key|sk-[A-Za-z0-9]{12}/i.test(html));
assert.ok(!/fetch\(.+cartesia|fetch\(.+elevenlabs|fetch\(.+api\.openai\.com/.test(js),'No paid voice requests from browser');
assert.ok(js.includes("provider!=='browser'"),'Paid previews must remain disabled');
console.log('Voice Studio static and security checks passed.');
